g_langStr=objJoin(g_langStr,{
		"zh-tw":{
			"IDS_STOP":"停止",
			"IDS_PLAY":"播放",
			"IDS_PAUSE":"暫停",
			"IDS_SFORWARD":"下一格",
			"IDS_SBACK":"前一格",
			"IDS_FORWARD":"快轉",
			"IDS_BACK":"減速",
			"IDS_CONNECTED":"己連線",
			"IDS_DISCONNECTED":"己斷線",
			"IDS_CONNECTING":"連線中",
			"IDS_DISCONNECTING":"斷線中",
			"IDS_STARTTIME":"開始時間",
			"IDS_LENGTH":"長度",
			"IDS_SHOWCTL":"顯示控制面版",
			"IDS_HIDECTL":"隱藏控制面版",
			"IDS_NOSERVER":"無法連結服務",
			"IDS_CHNAME":"頻道名稱",
			"IDS_BMPPATH":"快照儲存路徑",
			"IDS_VDOSAVEPATH":"錄影儲存路徑",
			"IDS_VDOSAVETYPE":"錄影儲存方式",
			"IDS_ONLYPLAY":"只播放",
			"IDS_ONLYSAVE":"只儲存",
			"IDS_PLAYSAVE":"邊播邊放",
			"IDS_SAVESETTING":"儲存設定",
			"IDS_RATIO":"影像比例 : ",
			"IDS_REPPLAY":"重複播放",
			"IDS_READY":"準備",
			"IDS_PLAYEND":"結束"
			},
		"en":{
			"IDS_STOP":"Stop",
			"IDS_PLAY":"Play",
			"IDS_PAUSE":"Pause",
			"IDS_SFORWARD":"Forware",
			"IDS_SBACK":"Back",
			"IDS_FORWARD":"FF",
			"IDS_BACK":"SlowDown",
			"IDS_CONNECTED":"Connected",
			"IDS_DISCONNECTED":"Disconnected",
			"IDS_CONNECTING":"Connecting",
			"IDS_DISCONNECTING":"Disconnecting",
			"IDS_STARTTIME":"Start Time",
			"IDS_LENGTH":"Length",
			"IDS_SHOWCTL":"Show Control Panel",
			"IDS_HIDECTL":"Hide Control Panel",
			"IDS_NOSERVER":"No Server",
			"IDS_CHNAME":"Channel Name",
			"IDS_BMPPATH":"SnapShot Save Path",
			"IDS_VDOSAVEPATH":"Video Save Path",
			"IDS_VDOSAVETYPE":"Video Save Way",
			"IDS_ONLYPLAY":"Just Playing",
			"IDS_ONLYSAVE":"Only Save",
			"IDS_PLAYSAVE":"Playing And Saving",
			"IDS_SAVESETTING":"Save Setting",
			"IDS_RATIO":"Video Ratio : ",
			"IDS_REPPLAY":"Play Repeatly",
			"IDS_READY":"Ready",
			"IDS_PLAYEND":"End"			
			}}[lang]);