// JavaScript Document
g_langStr=objJoin(g_langStr,{

	"IDC_TITLE":"Web 網頁客戶端登入",
	"IDC_ACCOUNT":"帳號:",
	"IDC_PASSWORD":"密碼:",
	"IDC_PORT":"連接埠:",
	"IDC_LOGIN":"登入",
	"IDC_AP_DOWNLOAD":"Client 軟體下載",
	"IDC_AP_CLIENT":"執行遠端監控程式",
	"IDC_STEP_TITLE":"自動旋轉",
	"IDC_STEP_1":"PTZ設定",
	"IDC_STEP_2":"自動掃描類型",
	"IDC_SER_INFO":"伺服器資訊",
	"IDC_BOTTOMPANEBG":"頻道選擇跟設定",
	"IDC_PTZ":"雲台控制",
	"IDC_DIVIDE_VIEW":"分割視窗:",
	"IDC_DISPLAY_RATIO":"顯示比例:",
	"IDC_ENABLE_AUDIO":"啟用聲音:",
	"IDC_DUAL_AUDIO":"雙向語音設定:",
	"IDC_ENABLE":"啟用",
	"IDC_DISABLE":"停用",
	"IDC_TIMEOUT":"逾時重試...",
	"IDC_IO_SETTING":"I/O設定:",
	"IDC_SHOW_CTRL":"顯示控制頁",
	"IDC_HIDE_CTRL":"隱藏控制頁",
	"IDC_STR_IO":"沒有I/O埠",
	"IDC_NO_CONNECTED":"沒有連線",
	"IDC_CONN_NAME":"帳號:/ 密碼:/ 來源伺服器:/ 連接埠",
	"IDC_SAVE_VIDEO":"儲存影像:",
	"IDC_SNAP":"單張捕捉:",
	"IDC_TYPE":"型別:",
	"IDC_CHANNEL":"頻道:",
	"IDC_VERSION":"版本:",
	"IDC_SERVER_CH":"伺服器頻道:",
	"IDC_SERVER_IP":"伺服器IP:",
	"IDC_SERVER_USER":"使用者:",
	"IDC_SERVER_VIDEO":"影像:",
	"IDC_SERVER_WIDTH":"寬:",
	"IDC_SERVER_HEIGHT":"高:",
	"IDC_CONNECT_STATUS":"連線狀態:",
	"IDC_CONNECT_TYPE":"連線方式:",
	"IDC_ALARM_EVENT":"警報事件:",
	"IDC_ALARM_MOTION":"動態異常事件",
	"IDC_ALARM_IO":"IO異常事件",
	"IDC_ALARM_VIDEOLOSE":"影像遺失事件",
	"IDC_NO_ALARM":"沒有警報",
	"IDC_HINT_NAME":"假如沒有看到任何的顯示畫面，請按照下列步驟去更改您的瀏覽器設定。請到瀏覽器的 ?\"工具\"，\"Internet選項\"，\"安全\"，\"信任的網站\"，並將 IP Camera的IP 填入，同時，請將\"安全級別\"為\"低\"。接著下載成功後，顯示畫面就會正常顯示。",
	"IDC_TITLE_BROWER_SETTING":"* 請遵循以下步驟來更改您的瀏覽器設定 : ",
	"IDC_FIRST_STEP_1":"首先將 SecurityEyes 的IP位址加到瀏覽器的信任網站列表中，請參考下列步驟 : ",
	"IDC_FIRST_STEP_2":"在瀏覽器的 \"工具\" 選單→點擊 \"網際網路選項\" → 點選\"安全性\"，點擊\"信任的網站\"→點擊\"網站\"按鈕→輸入SecurityEyes的IP位址到\"將此網站加到該區域中\"框中，取消\"此區域內的所有網站需要伺服器驗證(HTTPS)\"，然後點擊\"新增\"按鈕。",  
	"IDC_SECOND_STEP":"刷新網頁後，您會看到安裝ActiveX元件的提示，請安裝它。假如您看不到提示或者是看不到影像的話，你可以點擊<a href=\"RemoteClientWebSetup.exe\">Manually Download Web Client Control</a>手動下載安裝。",
	"IDC_LANGUAGE_SELECT":"選擇語言:",
	"IDC_LANGUAGE_ENGLISH":"英文",
	"IDC_LANGUAGE_TAIWAN":"中文(繁體)",
	"IDC_LANGUAGE_CHINA":"中文(簡體)",
	"IDC_LANGUAGE_FRENCH":"法文",
	"IDC_LANGUAGE_GERMANY":"德文",
	"IDC_LANGUAGE_ITALY":"義大利文",
	"IDC_LANGUAGE_JAPAN":"日文",
	"IDC_LANGUAGE_SPANISH":"西班牙文",
	"IDC_LANGUAGE_RUSSIA":"俄文",
	"IDC_TOOLTIP_BROWSE_VIDEO_FOLDER":"錄影檔路徑",
	"IDC_TOOLTIP_RECORDING":"開始/停止錄影",
	"IDC_TOOLTIP_BROWSE_SNAPSHOT_FOLDER":"單張捕捉路徑",
	"IDC_TOOLTIP_BROWSE_SNAPSHOT_FILE":"單張捕捉檔案",
	"IDC_TOOLTIP_BROWSE_CONNECTED":"連線/斷線",
	"IDC_TOOLTIP_APPLY_ALL":"套用到全部Channel",
	"IDC_PTZ_ZOOMIN":"倍數放大",
	"IDC_PTZ_ZOOMOUT":"倍數縮小",
	"IDC_PTZ_FOCUSFAR":"對焦變遠",
	"IDC_PTZ_FOCUSNEAR":"對焦變近",
	"IDC_PTZ_DIAPHRAGM_ADD":" 光圈變小",
	"IDC_PTZ_DIAPHRAGM_DEL":" 光圈變大",
	"IDC_PTZ_AUTO_FOCUS":"自動對焦",
	"IDC_PTZ_AUTO_CRUISE":"自動巡弋",
	"IDC_PTZ_SETTING":"設定",
	"IDC_CTRL_NORMAL":"一般",
	"IDC_CTRL_ZOOMIN":"倍數放大",
	"IDC_CTRL_ZOOMOUT":"倍數縮小",
	"IDC_CTRL_FLIPV":"垂直翻轉",
	"IDC_CTRL_FLIPH":"水平翻轉",
	"IDC_MAIN_STREAM":"主串流",
	"IDC_SUB_STREAM":"副串流",
	"IDC_SELECT_STREAM":"選擇串流 :  ",
	"IDC_SELECT_STREAM2":"選擇大畫面串流 :  "


});
